# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

name: Check for license presence
kind: pipeline
type: docker
node:
  performance: low
clone:
  depth: 1
steps:
  - name: check
    image: docker.io/library/golang:1.21
    pull: always
    commands:
      - go install github.com/google/addlicense@v1.1.1
      - addlicense -c "SIGHUP s.r.l" -v -l bsd -y "2017-present" --check .

---
name: Linting
kind: pipeline
type: docker
node:
  performance: low
depends_on:
  - Check for license presence
clone:
  depth: 1
platform:
  os: linux
  arch: amd64

environment:
  # Mise configuration
  MISE_DATA_DIR: "/mise-data"

volumes:
  - name: mise-cache
    host:
      path: /root/mise_data_dir
steps:
  - name: Render Manifests
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - clone
    commands:
      - mise use kustomize@5.6.0
      - eval "$(mise activate bash --shims)"
      - kustomize build katalog/cilium > cilium.yml
      - kustomize build katalog/tigera/on-prem > tigera-on-prem.yml

  - &check-deprecated-apis
    name: check-deprecated-apis-cilium
    image: us-docker.pkg.dev/fairwinds-ops/oss/pluto:v5
    pull: always
    depends_on:
      - Render Manifests
    commands:
      # we use --ignore-deprecations because we don't want the CI to fail when the API has not been removed yet.
      - /pluto detect $${KUBERNETES_MANIFESTS} --ignore-deprecations --target-versions=k8s=v1.33.0
    environment:
      KUBERNETES_MANIFESTS: cilium.yml

  - <<: *check-deprecated-apis
    name: check-deprecated-apis-tigera
    environment:
      KUBERNETES_MANIFESTS: tigera-on-prem.yml

---
name: E2E Tests Cilium K8s 1.31
kind: pipeline
type: docker
platform:
  os: linux
  arch: amd64
depends_on:
  - Linting
clone:
  depth: 1
trigger:
  ref:
    include:
      - refs/tags/**

environment:
  # Mise configuration
  MISE_DATA_DIR: "/mise-data"
  KIND_VERSION: "0.29.0"
  KUBECTL_VERSION: "1.31.1"
  BATS_VERSION: "1.11.0"
  CLUSTER_VERSION: "1.31.0"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: mise-cache
    host:
      path: /root/mise_data_dir
steps:
  - name: Create Kind Cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    depends_on:
      - clone
    commands:
      - mise use kind@${KIND_VERSION} kubectl@${KUBECTL_VERSION} kustomize@5.6.0
      - eval "$(mise activate bash --shims)"
      - ./scripts/create-e2e-cluster.sh cilium ${CLUSTER_VERSION}

  - name: Run E2E Tests
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - Create Kind Cluster
    commands:
      - mise use bats@${BATS_VERSION} kubectl@${KUBECTL_VERSION} kustomize@5.6.0
      - eval "$(mise activate bash --shims)"
      - ./scripts/run-cilium-tests.sh

  - name: Delete Kind Cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    depends_on:
      - Run E2E Tests
    when:
      status:
        - success
        - failure
    commands:
      - mise use kind@${KIND_VERSION}
      - eval "$(mise activate bash --shims)"
      - ./scripts/cleanup-e2e-cluster.sh || true

---
name: E2E Tests Cilium K8s 1.32
kind: pipeline
type: docker
platform:
  os: linux
  arch: amd64
depends_on:
  - Linting
clone:
  depth: 1
trigger:
  ref:
    include:
      - refs/tags/**

environment:
  # Mise configuration
  MISE_DATA_DIR: "/mise-data"
  KIND_VERSION: "0.29.0"
  KUBECTL_VERSION: "1.32.2"
  BATS_VERSION: "1.11.0"
  CLUSTER_VERSION: "1.32.2"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: mise-cache
    host:
      path: /root/mise_data_dir
steps:
  - name: Create Kind Cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    depends_on:
      - clone
    commands:
      - mise use kind@${KIND_VERSION} kubectl@${KUBECTL_VERSION} kustomize@5.6.0
      - eval "$(mise activate bash --shims)"
      - ./scripts/create-e2e-cluster.sh cilium ${CLUSTER_VERSION}

  - name: Run E2E Tests
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - Create Kind Cluster
    commands:
      - mise use bats@${BATS_VERSION} kubectl@${KUBECTL_VERSION} kustomize@5.6.0
      - eval "$(mise activate bash --shims)"
      - ./scripts/run-cilium-tests.sh

  - name: Delete Kind Cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    depends_on:
      - Run E2E Tests
    when:
      status:
        - success
        - failure
    commands:
      - mise use kind@${KIND_VERSION}
      - eval "$(mise activate bash --shims)"
      - ./scripts/cleanup-e2e-cluster.sh || true

---
name: E2E Tests Cilium K8s 1.33
kind: pipeline
type: docker
platform:
  os: linux
  arch: amd64
depends_on:
  - Linting
clone:
  depth: 1
trigger:
  ref:
    include:
      - refs/tags/**

environment:
  # Mise configuration
  MISE_DATA_DIR: "/mise-data"
  KIND_VERSION: "0.29.0"
  KUBECTL_VERSION: "1.33.4"
  BATS_VERSION: "1.11.0"
  CLUSTER_VERSION: "1.33.0"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: mise-cache
    host:
      path: /root/mise_data_dir
steps:
  - name: Create Kind Cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    depends_on:
      - clone
    commands:
      - mise use kind@${KIND_VERSION} kubectl@${KUBECTL_VERSION} kustomize@5.6.0
      - eval "$(mise activate bash --shims)"
      - ./scripts/create-e2e-cluster.sh cilium ${CLUSTER_VERSION}

  - name: Run E2E Tests
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - Create Kind Cluster
    commands:
      - mise use bats@${BATS_VERSION} kubectl@${KUBECTL_VERSION} kustomize@5.6.0
      - eval "$(mise activate bash --shims)"
      - ./scripts/run-cilium-tests.sh

  - name: Delete Kind Cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    depends_on:
      - Run E2E Tests
    when:
      status:
        - success
        - failure
    commands:
      - mise use kind@${KIND_VERSION}
      - eval "$(mise activate bash --shims)"
      - ./scripts/cleanup-e2e-cluster.sh || true

---
name: E2E Tests Tigera K8s 1.31
kind: pipeline
type: docker
platform:
  os: linux
  arch: amd64
depends_on:
  - Linting
clone:
  depth: 1
trigger:
  ref:
    include:
      - refs/tags/**

environment:
  # Mise configuration
  MISE_DATA_DIR: "/mise-data"
  KIND_VERSION: "0.29.0"
  KUBECTL_VERSION: "1.31.1"
  BATS_VERSION: "1.11.0"
  CLUSTER_VERSION: "1.31.0"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: mise-cache
    host:
      path: /root/mise_data_dir
steps:
  - name: Create Kind Cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    depends_on:
      - clone
    commands:
      - mise use kind@${KIND_VERSION} kubectl@${KUBECTL_VERSION} kustomize@5.6.0
      - eval "$(mise activate bash --shims)"
      - ./scripts/create-e2e-cluster.sh tigera ${CLUSTER_VERSION}

  - name: Run E2E Tests
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - Create Kind Cluster
    commands:
      - mise use bats@${BATS_VERSION} kubectl@${KUBECTL_VERSION} kustomize@5.6.0
      - eval "$(mise activate bash --shims)"
      - ./scripts/run-tigera-tests.sh

  - name: Delete Kind Cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    depends_on:
      - Run E2E Tests
    when:
      status:
        - success
        - failure
    commands:
      - mise use kind@${KIND_VERSION}
      - eval "$(mise activate bash --shims)"
      - ./scripts/cleanup-e2e-cluster.sh || true

---
name: E2E Tests Tigera K8s 1.32
kind: pipeline
type: docker
platform:
  os: linux
  arch: amd64
depends_on:
  - Linting
clone:
  depth: 1
trigger:
  ref:
    include:
      - refs/tags/**

environment:
  # Mise configuration
  MISE_DATA_DIR: "/mise-data"
  KIND_VERSION: "0.29.0"
  KUBECTL_VERSION: "1.32.2"
  BATS_VERSION: "1.11.0"
  CLUSTER_VERSION: "1.32.2"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: mise-cache
    host:
      path: /root/mise_data_dir
steps:
  - name: Create Kind Cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    depends_on:
      - clone
    commands:
      - mise use kind@${KIND_VERSION} kubectl@${KUBECTL_VERSION} kustomize@5.6.0
      - eval "$(mise activate bash --shims)"
      - ./scripts/create-e2e-cluster.sh tigera ${CLUSTER_VERSION}

  - name: Run E2E Tests
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - Create Kind Cluster
    commands:
      - mise use bats@${BATS_VERSION} kubectl@${KUBECTL_VERSION} kustomize@5.6.0
      - eval "$(mise activate bash --shims)"
      - ./scripts/run-tigera-tests.sh

  - name: Delete Kind Cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    depends_on:
      - Run E2E Tests
    when:
      status:
        - success
        - failure
    commands:
      - mise use kind@${KIND_VERSION}
      - eval "$(mise activate bash --shims)"
      - ./scripts/cleanup-e2e-cluster.sh || true

---
name: E2E Tests Tigera K8s 1.33
kind: pipeline
type: docker
platform:
  os: linux
  arch: amd64
depends_on:
  - Linting
clone:
  depth: 1
trigger:
  ref:
    include:
      - refs/tags/**

environment:
  # Mise configuration
  MISE_DATA_DIR: "/mise-data"
  KIND_VERSION: "0.29.0"
  KUBECTL_VERSION: "1.33.4"
  BATS_VERSION: "1.11.0"
  CLUSTER_VERSION: "1.33.0"

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: mise-cache
    host:
      path: /root/mise_data_dir
steps:
  - name: Create Kind Cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    depends_on:
      - clone
    commands:
      - mise use kind@${KIND_VERSION} kubectl@${KUBECTL_VERSION} kustomize@5.6.0
      - eval "$(mise activate bash --shims)"
      - ./scripts/create-e2e-cluster.sh tigera ${CLUSTER_VERSION}

  - name: Run E2E Tests
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: mise-cache
        path: /mise-data
    depends_on:
      - Create Kind Cluster
    commands:
      - mise use bats@${BATS_VERSION} kubectl@${KUBECTL_VERSION} kustomize@5.6.0
      - eval "$(mise activate bash --shims)"
      - ./scripts/run-tigera-tests.sh

  - name: Delete Kind Cluster
    image: quay.io/sighup/mise:v2025.4.4
    pull: always
    network_mode: host
    environment:
      GITHUB_TOKEN:
        from_secret: github_token
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: mise-cache
        path: /mise-data
    depends_on:
      - Run E2E Tests
    when:
      status:
        - success
        - failure
    commands:
      - mise use kind@${KIND_VERSION}
      - eval "$(mise activate bash --shims)"
      - ./scripts/cleanup-e2e-cluster.sh || true
---
name: release
kind: pipeline
type: docker
node:
  performance: low
clone:
  depth: 1
depends_on:
  - E2E Tests Cilium K8s 1.31
  - E2E Tests Cilium K8s 1.32
  - E2E Tests Cilium K8s 1.33
  - E2E Tests Tigera K8s 1.31
  - E2E Tests Tigera K8s 1.32
  - E2E Tests Tigera K8s 1.33
platform:
  os: linux
  arch: amd64
trigger:
  ref:
    include:
      - refs/tags/**
    exclude:
      - refs/tags/e2e-**
steps:
  - name: prepare-tar-gz
    image: alpine:latest
    pull: always
    depends_on: [clone]
    commands:
      - tar -zcvf fury-kubernetes-networking-${DRONE_TAG}.tar.gz katalog/ LICENSE README.md
    when:
      ref:
        include:
          - refs/tags/**

  - name: prepare-release-notes
    image: quay.io/sighup/fury-release-notes-plugin:3.7_2.8.4
    pull: always
    depends_on: [clone]
    settings:
      release_notes_file_path: release-notes.md
    when:
      ref:
        include:
          - refs/tags/**

  - name: publish-prerelease
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-tar-gz
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: overwrite
      files:
        - fury-kubernetes-networking-${DRONE_TAG}.tar.gz
      prerelease: true
      overwrite: true
      title: "Preview ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        include:
          - refs/tags/v**-rc**

  - name: publish-stable
    image: plugins/github-release
    pull: always
    depends_on:
      - prepare-tar-gz
      - prepare-release-notes
    settings:
      api_key:
        from_secret: github_token
      file_exists: overwrite
      files:
        - fury-kubernetes-networking-${DRONE_TAG}.tar.gz
      prerelease: false
      overwrite: true
      title: "Release ${DRONE_TAG}"
      note: release-notes.md
      checksum:
        - md5
        - sha256
    when:
      ref:
        exclude:
          - refs/tags/v**-rc**
        include:
          - refs/tags/v**
